import Link from 'next/link'
import {
  IconPresentation,
  IconPhoto,
  IconClipboardList,
  IconCode,
  IconArrowRight,
} from '@tabler/icons-react'
import { Button } from '@/components/ui/button'

type Feature = {
  icon: React.ElementType
  tag: string
  title: string
  description: string
  bullets: string[]
  href: string
  mockup: React.ReactNode
  flip: boolean
}

const features: Feature[] = [
  {
    icon: IconPresentation,
    tag: 'Slide Studio',
    title: 'From prompt to pitch deck in seconds',
    description:
      'Describe your event and EventForge generates a full Marp presentation — structured slides, theme, and layout — ready to edit and share.',
    bullets: [
      'Marp Markdown under the hood, full CSS control',
      'Edit any slide with natural language instructions',
      'Export or present directly in the browser',
    ],
    href: '/slides',
    flip: false,
    mockup: (
      <div className="w-full border border-border bg-zinc-900 p-5 shadow-lg">
        {/* Slide header */}
        <div className="mb-4 flex items-center justify-between">
          <div className="flex gap-1">
            <div className="h-1.5 w-1.5 bg-zinc-600" />
            <div className="h-1.5 w-1.5 bg-zinc-600" />
            <div className="h-1.5 w-1.5 bg-zinc-600" />
          </div>
          <div className="h-1.5 w-16 bg-zinc-700" />
        </div>
        {/* Slide content */}
        <div className="bg-zinc-800 px-6 py-8">
          <div className="mb-1 h-1 w-16 bg-primary" />
          <div className="mb-3 h-5 w-4/5 bg-white" />
          <div className="mb-6 h-3 w-3/5 bg-white/40" />
          <div className="space-y-2">
            {[75, 60, 80].map((w) => (
              <div key={w} className="flex items-center gap-2">
                <div className="h-1.5 w-1.5 bg-primary" />
                <div className="h-2" style={{ width: `${w}%`, background: 'rgba(255,255,255,0.25)' }} />
              </div>
            ))}
          </div>
        </div>
        {/* Slide nav */}
        <div className="mt-3 flex items-center justify-center gap-1">
          {[0, 1, 2, 3, 4].map((i) => (
            <div key={i} className={`h-1 ${i === 1 ? 'w-4 bg-primary' : 'w-1 bg-zinc-600'}`} />
          ))}
        </div>
      </div>
    ),
  },
  {
    icon: IconPhoto,
    tag: 'Media Studio',
    title: 'Generate event media from one brief',
    description:
      'Input your event description and get a promotional poster, background soundtrack, and social copy — all generated by AI in one session.',
    bullets: [
      'AI poster generation via Wanx image model',
      'Instrumental soundtrack from Minimax music API',
      'Social copy and promotional text included',
    ],
    href: '/media',
    flip: true,
    mockup: (
      <div className="w-full border border-border bg-zinc-900 p-5 shadow-lg">
        {/* Poster */}
        <div className="mb-3 aspect-[4/3] bg-zinc-800 p-4">
          <div className="mb-2 h-2 w-2/3 bg-primary/60" />
          <div className="mb-4 h-1.5 w-2/5 bg-white/30" />
          <div className="grid grid-cols-3 gap-1">
            <div className="col-span-2 row-span-2 bg-zinc-700" style={{ height: 56 }} />
            <div className="bg-primary/30" style={{ height: 26 }} />
            <div className="bg-zinc-600" style={{ height: 26 }} />
          </div>
        </div>
        {/* Music waveform */}
        <div className="flex items-end gap-px px-2" style={{ height: 28 }}>
          {[4, 8, 14, 10, 18, 12, 20, 16, 10, 14, 8, 18, 12, 6, 16, 20, 10, 14].map(
            (h, i) => (
              <div
                key={i}
                className="flex-1 bg-primary/60"
                style={{ height: h }}
              />
            ),
          )}
        </div>
        <div className="mt-2 text-center text-[9px] text-zinc-500">Soundtrack preview</div>
      </div>
    ),
  },
  {
    icon: IconClipboardList,
    tag: 'Surveys',
    title: 'Interactive surveys with live analytics',
    description:
      'Build surveys in minutes, share a link, and watch responses roll in with real-time charts and response details.',
    bullets: [
      'Drag-and-drop question builder',
      'Embed custom AI-generated question types',
      'Live response dashboard with trends',
    ],
    href: '/surveys',
    flip: false,
    mockup: (
      <div className="w-full border border-border bg-background p-5 shadow-lg">
        {/* Question */}
        <div className="mb-4 border-b border-border pb-4">
          <div className="mb-2 h-2 w-4/5 bg-foreground/80" />
          <div className="space-y-2 pt-1">
            {['Option A', 'Option B', 'Option C'].map((opt, i) => (
              <div key={opt} className="flex items-center gap-2">
                <div
                  className={`h-3 w-3 border ${i === 1 ? 'border-primary bg-primary/15' : 'border-border'}`}
                />
                <div className={`h-2 ${i === 1 ? 'bg-foreground/60' : 'bg-muted-foreground/30'}`}
                  style={{ width: i === 0 ? '45%' : i === 1 ? '55%' : '35%' }}
                />
              </div>
            ))}
          </div>
        </div>
        {/* Mini bar chart */}
        <div className="text-[9px] text-muted-foreground mb-1.5">Responses (24)</div>
        <div className="flex items-end gap-1.5" style={{ height: 40 }}>
          {[60, 30, 10].map((pct, i) => (
            <div key={i} className="flex flex-1 flex-col items-center gap-1">
              <div
                className={`w-full ${i === 0 ? 'bg-primary' : 'bg-primary/30'}`}
                style={{ height: (pct / 100) * 36 }}
              />
              <span className="text-[8px] text-muted-foreground">{pct}%</span>
            </div>
          ))}
        </div>
      </div>
    ),
  },
  {
    icon: IconCode,
    tag: 'Question Types',
    title: 'AI writes custom question components',
    description:
      'Describe the interaction you want — rating scale, image picker, voice recorder — and AI generates a fully working React component, instantly deployable in any survey.',
    bullets: [
      'Natural language → React component',
      'Runs safely in a sandboxed scope',
      'Supports AI hooks: chat, image gen, music gen',
    ],
    href: '/question-types',
    flip: true,
    mockup: (
      <div className="w-full border border-border shadow-lg">
        {/* Code editor */}
        <div className="bg-zinc-900 p-4">
          <div className="mb-2 flex gap-1">
            <div className="h-1.5 w-1.5 bg-zinc-600" />
            <div className="h-1.5 w-1.5 bg-zinc-600" />
            <div className="h-1.5 w-1.5 bg-zinc-600" />
          </div>
          <div className="font-mono text-[10px] leading-5">
            <span className="text-zinc-500">// AI-generated component</span>
            <br />
            <span className="text-primary">function</span>
            <span className="text-white"> StarRating</span>
            <span className="text-zinc-400">{'() {'}</span>
            <br />
            <span className="text-zinc-500 pl-4">const [val, setVal] =</span>
            <br />
            <span className="text-primary pl-6">useState</span>
            <span className="text-zinc-400">(0)</span>
            <br />
            <span className="text-zinc-400 pl-4">{'return ('}</span>
            <br />
            <span className="text-primary pl-6">{'<Stars'}</span>
            <span className="text-zinc-400">{' value={val} />'}</span>
          </div>
        </div>
        {/* Rendered preview */}
        <div className="border-t border-border bg-background px-4 py-3">
          <div className="mb-1 text-[9px] text-muted-foreground">Preview</div>
          <div className="flex gap-1">
            {[1, 2, 3, 4, 5].map((i) => (
              <div
                key={i}
                className={`text-base ${i <= 3 ? 'text-primary' : 'text-muted'}`}
              >
                ★
              </div>
            ))}
          </div>
        </div>
      </div>
    ),
  },
]

export function FeaturesSection() {
  return (
    <section className="px-4 py-16 md:py-24">
      <div className="mx-auto max-w-6xl space-y-28">
        {features.map(({ icon: Icon, tag, title, description, bullets, href, mockup, flip }) => (
          <div
            key={tag}
            className={`flex flex-col items-center gap-12 md:flex-row ${flip ? 'md:flex-row-reverse' : ''}`}
          >
            {/* Text */}
            <div className="flex-1">
              <div className="mb-4 inline-flex items-center gap-2 border border-primary/20 bg-primary/8 px-3 py-1 text-xs font-semibold text-primary">
                <Icon size={13} />
                {tag}
              </div>
              <h3 className="mb-3 text-2xl font-bold tracking-tight md:text-3xl">{title}</h3>
              <p className="mb-5 text-muted-foreground leading-relaxed">{description}</p>
              <ul className="mb-6 space-y-2">
                {bullets.map((b) => (
                  <li key={b} className="flex items-start gap-2 text-sm text-muted-foreground">
                    <div className="mt-1.5 h-1.5 w-1.5 shrink-0 bg-primary" />
                    {b}
                  </li>
                ))}
              </ul>
              <Button variant="outline" size="sm" asChild>
                <Link href={href}>
                  Open {tag}
                  <IconArrowRight size={14} />
                </Link>
              </Button>
            </div>

            {/* Mockup */}
            <div className="w-full flex-1 md:max-w-[420px]">{mockup}</div>
          </div>
        ))}
      </div>
    </section>
  )
}
